class Menu1:
    print("----------------------------------------------------" )
    print(" |----------------------|    |----------------------|")
    print(" |     B U R G E R      |    |    JUICE/SOFDRINCK   |")
    print(" |----------------------|    |----------------------|")
    print(" |1.Veg.Burger    $: 6/-|    |1.Orange        $: 3/-|")
    print(" |2.chicken Burger$: 7/-|    |2.Coconut       $: 5/-|")
    print(" |3.American      ______|    |3.Mango         $:10/-|")
    print(" |  cheese Burger $: 8/-|    |4.Pomagranet    $: 2/-|")
    print(" |4.Chocolat      ______|    |5.Pepsi         $: 2/-|")
    print(" |         Burger $: 7/-|    |6.Cocakola      $: 2/-|")
    print(" |5.Minion Burger $: 4/-|    |7.Sprite        $: 2/-|")
    print(" |6.Maxican Burger$: 6/-|    |----------------------|")
    print(" |7.Special INDIAN______|    |        EXTRAS        |")
    print(" |  Burger        $: 8/-|    |----------------------|")
    print(" |8.Green Burger  $: 5/-|    |1.Seezling cheez      |")
    print(" |----------------------|    |  Potatos       $: 5/-|")
    print("                             |2.French Fries  $: 5/-|")
    print(" |----------------------|    |3.Mashed Potatos$: 5/-|")
    print(" |      SANDWICH        |    |4.Chili Fries   $: 5/-|")
    print(" |----------------------|    |5.Potato nugets $: 5/-|")
    print(" |1.Veg.Sandwich  $: 5/-|    |6.chili fills   $: 5/-|")
    print(" |2.Chicken       ______|    |7.Chicken wings $: 6/-|")
    print(" |  Sandwich      $: 6/-|    |8.Fride Chicken $: 6/-|")
    print(" |3.Paneer        ______|    |9.Chicken nugets$: 7/-|")
    print(" |  Sandwich      $: 6/-|    |----------------------|")
    print(" |4.egg.Sandwich  $: 3/-|")
    print(" |5.Grilled Extra ______|    |----------------------|")
    print(" |  Cheese        ______|    |      WRAPS           |")
    print(" |      Sandwich  $: 8/-|    |----------------------|")
    print(" |6.Maxican       ______|    |1.Paneer Wrap   $:10/-|")
    print(" |  Sandwich      $: 5/-|    |2.Chicken Wrap  $:10/-|")
    print(" |7.Chocolat      ______|    |3.egg.Wrap      $: 5/-|")
    print(" |   Sandwich     $: 4/-|    |4.Chocolat Wrap $:11/-|")
    print(" |8.French Toste  ______|    |----------------------|")
    print(" |Cheese Sandwich $: 5/-|")
    print(" |9.Famli size    ______|    |----------------------|")
    print(" |  Sandwich      $: 6/-|    |      DIPS            |")
    print(" |10.Club Sandwich$: 5/-|    |----------------------|")
    print(" |11.Jumbo size   ______|    |1.Cream&Onion   $: 1/-|")
    print(" |   three layered______|    |2.Cream Cheese  $: 1/-|")
    print(" |   Sandwich     $: 8/-|    |3.Chocochip     ______|")
    print(" |12.Barbeque     ______|    |  Cream         $: 2/-|")
    print(" |   Sandwich     $: 9/-|    |4.Smoked Cheese $: 2/-|")
    print(" |13.Kids Sandwich$: 3/-|    |5.Heavy cheez   $: 2/-|")
    print(" |14.diet Sandwich$: 4/-|    |6.Seezling cheez$: 1/-|")
    print(" |----------------------|    |----------------------|")
